--  Configuration for ada_rts_for_zfp_realtime_calendar generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Ada_Rts_For_Zfp_Realtime_Calendar_Config is
   pragma Pure;

   Crate_Version : constant String := "0.0.0";
   Crate_Name : constant String := "ada_rts_for_zfp_realtime_calendar";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "arch";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Ada_Rts_For_Zfp_Realtime_Calendar_Config;
