/* Configuration for ada_rts_for_zfp_realtime_calendar generated by Alire */
#ifndef ADA_RTS_FOR_ZFP_REALTIME_CALENDAR_CONFIG_H
#define ADA_RTS_FOR_ZFP_REALTIME_CALENDAR_CONFIG_H

#define CRATE_VERSION "0.0.0"
#define CRATE_NAME "ada_rts_for_zfp_realtime_calendar"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "arch"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
